# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)
sudo: required 
dist: trusty 
language: generic 
env:
  - ROS_DISTRO="kinetic"
install:
  - git clone --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci  
script: 
  - while sleep 5m; do echo "=====[ $SECONDS seconds, buildroot still building... ]====="; done &
  - .industrial_ci/ci.sh
  # Killing background sleep loop
  - kill %1
